name: Stale Pull Request

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'
  
jobs:
  stale-pr-reminder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
     - name: Generate token
       id: generate_token
       uses: tibdex/github-app-token@v1.8.0
       with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         token: ${{ steps.generate_token.outputs.token }}
         
     - name: comment on the pr.
       uses: actions/stale@v9
       with:
          repo-token: ${{ secrets.AWS_PAT }}
          stale-pr-message: 'This PR is stale because it has been open 5 days with no activity. update the pull request otherwise this will be closed in 1 day.'
          days-before-pr-stale: 5
          
     - name: stale and close the pr.
       uses: actions/stale@v9
       # with:
          # repo-token: ${{ secrets.AWS_PAT }}
          # # stale-pr-message: 'This PR is stale because it has been open 5 days with no activity. update the pull request otherwise this will be closed in 1 day.'
          # close-pr-message: 'This PR was closed because it has been staled for 5 days with no activity.'
          # # days-before-pr-stale: 5
          # days-before-pr-close: 0
    
