name: Stale Pull Request

on:
  workflow_dispatch:
  
jobs:
  stale-pr-reminder:
    runs-on: ubuntu-latest

    steps:
     - name: Generate token
       id: generate_token
       uses: tibdex/github-app-token@v1.8.0
       with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         token: ${{ steps.generate_token.outputs.token }}
         
     - name: Bash Script
       run: |
         GITHUB_OWNER="Akshaya222"
         GITHUB_REPO="ecs-github-actions"
         ACCESS_TOKEN=${{ steps.generate_token.outputs.token }}
         BOT_USERNAME="Bot"
      
         # Fetch open pull requests
         PR_LIST=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls?state=open&sort=pushed_at&direction=asc")

         # Filter pull requests pushed to 3, 6, and 9 minutes ago
         PR_LIST_3_MINUTES=$(echo "$PR_LIST" | jq -r ".[] | select(.pushed_at | strings | contains(\"$(date -u -d '3 minutes ago' +%Y-%m-%dT%H:%M)\")) | .number")
         PR_LIST_6_MINUTES=$(echo "$PR_LIST" | jq -r ".[] | select(.pushed_at | strings | contains(\"$(date -u -d '6 minutes ago' +%Y-%m-%dT%H:%M)\")) | .number")
         PR_LIST_9_MINUTES=$(echo "$PR_LIST" | jq -r ".[] | select(.pushed_at | strings | contains(\"$(date -u -d '9 minutes ago' +%Y-%m-%dT%H:%M)\")) | .number")


         echo "pr list pushed 3 minutes ago - ${PR_LIST_3_MINUTES}"
         echo "pr list pushed 6 minutes ago - ${PR_LIST_6_MINUTES}"
         echo "pr list pushed 9 minutes ago - ${PR_LIST_9_MINUTES}"

         # Loop through the list of pull requests and add comments or close them
         for PR_NUMBER_3 in $PR_LIST_3_MINUTES; do
          COMMENT=":rotating_light: **Reminder**: This pull request (#$PR_NUMBER_3) will be closed in 6 minutes if there's no further activity. Please review and provide any necessary updates. :rotating_light:"
          curl -s -H "Authorization: token $ACCESS_TOKEN" -X POST -d '{"body":"'"$COMMENT"'"}' "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/issues/$PR_NUMBER_3/comments"
         done

         for PR_NUMBER_6 in $PR_LIST_6_MINUTES; do
           COMMENT=":rotating_light: **Reminder**: This pull request (#$PR_NUMBER_6) will be closed in 3 minutes if there's no further activity. Please review and provide any necessary updates. :rotating_light:"
           curl -s -H "Authorization: token $ACCESS_TOKEN" -X POST -d '{"body":"'"$COMMENT"'"}' "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/issues/$PR_NUMBER_6/comments"
         done

         for PR_NUMBER_9 in $PR_LIST_9_MINUTES; do
           COMMENT=":rotating_light: **Closing**: Closing this pull request (#$PR_NUMBER_9) as it was inactive for more than 9 minutes. Feel free to reopen if needed. :rotating_light:"
           curl -s -H "Authorization: token $ACCESS_TOKEN" -X POST -d '{"body":"'"$COMMENT"'"}' "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/issues/$PR_NUMBER_9/comments"
           curl -s -H "Authorization: token $ACCESS_TOKEN" -X PATCH -d '{"state": "closed"}' "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls/$PR_NUMBER_9"
         done

         echo "*********************"
         CURRENT_TIME=$(date -u +"%Y-%m-%dT%H:%M")
         echo "current time is ${CURRENT_TIME}"
         echo "Pr is ${PR_LIST}"
