name: Stale Pull Request

on:
  workflow_dispatch: 
  
jobs:
  stale-reminder-16th-minute:
    runs-on: ubuntu-latest

    steps:
     - name: Generate token
       id: generate_token
       uses: tibdex/github-app-token@v1.8.0
       with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         token: ${{ steps.generate_token.outputs.token }}
         
     - name: Bash Script
       run: |
         GITHUB_OWNER="Akshaya222"
         GITHUB_REPO="ecs-github-actions"
         ACCESS_TOKEN=${{ steps.generate_token.outputs.token }}
         MINUTES_2_AGO=$(date -u -d "2 minutes ago" +%Y-%m-%dT%H:%M:%SZ)
         MINUTES_4_AGO=$(date -u -d "4 minutes ago" +%Y-%m-%dT%H:%M:%SZ)
         MINUTES_5_AGO=$(date -u -d "5 minutes ago" +%Y-%m-%dT%H:%M:%SZ)
         PR_LIST_2_MINUTES=$(curl -s -H "Authorization: token ${ACCESS_TOKEN}" "https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls?state=open&sort=updated&direction=asc" | jq -r ".[] | select(.updated_at < \"$MINUTES_2_AGO\") | .number")
         PR_LIST_4_MINUTES=$(curl -s -H "Authorization: token ${ACCESS_TOKEN}" "https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls?state=open&sort=updated&direction=asc" | jq -r ".[] | select(.updated_at < \"$MINUTES_4_AGO\") | .number")
         PR_LIST_5_MINUTES=$(curl -s -H "Authorization: token ${ACCESS_TOKEN}" "https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/pulls?state=open&sort=updated&direction=asc" | jq -r ".[] | select(.updated_at < \"$MINUTES_5_AGO\") | .number")
         echo "${PR_LIST_2_MINUTES}"
         echo "${PR_LIST_4_MINUTES}"
         echo "${PR_LIST_5_MINUTES}"
        
         
         
