name: Stale Pull Request

on:
  schedule:
    - cron: '* * * * *'  # Run every minute

jobs:
  stale-reminder-16th-minute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stale Check (16th minute reminder)
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          minutes-before-stale: 2
          minutes-before-close: 3

  stale-reminder-30th-minute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stale Check (30th minute reminder)
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          minutes-before-stale: 5
          minutes-before-close: 1
