name: Stale Pull Request

on:
  workflow_dispatch:
  
jobs:
  stale-reminder-16th-minute:
    runs-on: ubuntu-latest

    steps:
     - name: Generate token
       id: generate_token
       uses: tibdex/github-app-token@v1.8.0
       with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         token: ${{ steps.generate_token.outputs.token }}
         
     - name: Bash Script
       run: |
         GITHUB_OWNER="Akshaya222"
         GITHUB_REPO="ecs-github-actions"
         ACCESS_TOKEN=${{ steps.generate_token.outputs.token }}
         MINUTES_5_AGO=$(date -u -d "5 minutes ago" +%Y-%m-%dT%H:%M)
         MINUTES_10_AGO=$(date -u -d "10 minutes ago" +%Y-%m-%dT%H:%M)
         MINUTES_15_AGO=$(date -u -d "15 minutes ago" +%Y-%m-%dT%H:%M)
         echo "minutes 5 ago is - ${MINUTES_5_AGO}"
         echo "minutes 10 ago is - ${MINUTES_10_AGO}"
         echo "minutes 15 ago is - ${MINUTES_15_AGO}"
         PR_LIST_5_MINUTES=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls?state=open&sort=updated&direction=asc" | jq -r ".[] | select(.updated_at | startswith(\"$MINUTES_5_AGO\")) | .number")
         PR_LIST_10_MINUTES=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls?state=open&sort=updated&direction=asc" | jq -r ".[] | select(.updated_at | startswith(\"$MINUTES_10_AGO\")) | .number")
         PR_LIST_15_MINUTES=$(curl -s -H "Authorization: token $ACCESS_TOKEN" "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls?state=open&sort=updated&direction=asc" | jq -r ".[] | select(.updated_at | startswith(\"$MINUTES_15_AGO\")) | .number")
         for PR_NUMBER_1 in $PR_LIST_5_MINUTES; do
         COMMENT="Reminder**: This pull request will be closed in 10 minutes if there's no further activity. Please review and provide any necessary updates."
         curl -s -H "Authorization: token $ACCESS_TOKEN" -X POST -d '{"body":"'"$COMMENT"'"}' "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/issues/$PR_NUMBER_1/comments"
         done
         for PR_NUMBER_2 in $PR_LIST_10_MINUTES; do
         COMMENT="Reminder**: This pull request will be closed in 5 minutes if there's no further activity. Please review and provide any necessary updates."
         curl -s -H "Authorization: token $ACCESS_TOKEN" -X POST -d '{"body":"'"$COMMENT"'"}' "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/issues/$PR_NUMBER_2/comments"
         done
         for PR_NUMBER_3 in $PR_LIST_15_MINUTES; do
         COMMENT=" Closing**: closing this pr as it was inactive for more than 15 minutes. Feel free to reopen if needed."
         curl -s -H "Authorization: token $ACCESS_TOKEN" -X POST -d '{"body":"'"$COMMENT"'"}' "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/issues/$PR_NUMBER_3/comments"
         curl -s -H "Authorization: token $ACCESS_TOKEN" -X PATCH -d '{"state": "closed"}' "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls/$PR_NUMBER_3"
         done

         
         
        
         
         
